import { Header, Footer } from "@/components";
import "./globals.scss";

export const metadata = {
  title: "Asosiasi Emiten Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <section>{children}</section>
        <Footer />
      </body>
    </html>
  );
}
