import { Header, Footer } from "@/components";
import {ClientLayout} from '@/components';
import './globals.scss';

export const metadata = {
  title: 'Asosiasi Emiten Indonesia',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body>
        <ClientLayout>
          <Header />
            <section>{children}</section>
          <Footer />
        </ClientLayout>
      </body>
    </html>
  );
}
